version: "3"
   
services:
  custom-activation:
    restart: always
    build: .
    container_name: custom-activation-rsa
    command: bash run.sh
    volumes:
      - .:/custom-activation
    network_mode: host